// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
//
// Opening the sealed box the server puts a push preview inside.
//
// The server seals with the `crypto_box` crate's `PublicKey::seal`, which is
// libsodium's anonymous sealed box: X25519 to agree a key with a throwaway
// sender keypair, HSalsa20 to turn that into a box key, XSalsa20 for the
// stream and Poly1305 for the tag, with a BLAKE2b-derived nonce.
//
// CryptoKit has exactly one of those five: X25519. It has no Salsa family, no
// Poly1305 on its own, and no BLAKE2b, so Blake2b.swift, Salsa20.swift and
// Poly1305.swift implement the rest from their specifications. That is a real
// cost and it was weighed: the alternative is a native dependency for one
// extension, and this repository does not even commit a Podfile, so adding
// one would mean pinning a generated file and shipping a framework into an
// app extension the store refuses to see one in (error 90206).
//
// The mitigation is that none of it is trusted on reasoning alone.
// RunnerTests/PushSealedBoxTests.swift opens real ciphertext generated by the
// server's own crate, from a fixture committed by
// crates/slimm-server/tests/push_envelope_fixture.rs, and that test runs on a
// macOS runner in client-ios-ci.
//
// Failing to open is never fatal here. Everything above returns nil rather
// than throwing, and NotificationService.swift shows the relay's own generic
// string instead - a wrong guess must degrade to "New message", never to no
// notification at all.

import CryptoKit
import Foundation

enum PushSealedBox {
  /// A sealed box is the sender's throwaway public key, then the tag, then
  /// the ciphertext. The tag leads rather than trails: that is libsodium's
  /// order, which the server's crate follows, and not the order the same
  /// crate's generic AEAD interface would otherwise have used.
  private static let ephemeralKeyBytes = 32
  private static let tagBytes = 16
  private static let nonceBytes = 24

  /// Opens `sealed` with this device's X25519 private key, or nil if it was
  /// not sealed to this key, was tampered with, or is malformed.
  ///
  /// `privateKey` is the raw 32-byte value the app stored, unclamped;
  /// CryptoKit clamps it on use, exactly as the server's scalar
  /// multiplication does.
  static func open(_ sealed: [UInt8], privateKey: [UInt8]) -> [UInt8]? {
    guard privateKey.count == 32,
      sealed.count >= ephemeralKeyBytes + tagBytes
    else { return nil }

    let ephemeralPublic = Array(sealed[0..<ephemeralKeyBytes])
    let tag = Array(sealed[ephemeralKeyBytes..<(ephemeralKeyBytes + tagBytes)])
    let ciphertext = Array(sealed[(ephemeralKeyBytes + tagBytes)...])

    guard let agreement = sharedSecret(
      privateKey: privateKey,
      ephemeralPublic: ephemeralPublic
    ) else { return nil }

    // The nonce is derived from both public keys rather than sent, which
    // is what lets a sealed box carry no nonce of its own. Our own public
    // key has to be recomputed from the private one for this.
    let nonce = Blake2b.hash(
      ephemeralPublic + agreement.recipientPublic,
      digestLength: nonceBytes
    )

    let boxKey = Salsa20.hsalsa20(
      key: agreement.shared,
      input16: [UInt8](repeating: 0, count: 16)
    )
    let streamKey = Salsa20.hsalsa20(key: boxKey, input16: Array(nonce[0..<16]))
    let iv = Array(nonce[16..<nonceBytes])

    // The first 32 bytes of the keystream are spent on the one-time
    // authenticator key, so the message starts at byte 32 - halfway
    // through the same block, not at the start of the next one.
    let authKey = Salsa20.keystream(key: streamKey, iv8: iv, offset: 0, count: 32)
    let expected = Poly1305.authenticate(message: ciphertext, key: authKey)
    guard Poly1305.constantTimeEquals(tag, expected) else { return nil }

    let stream = Salsa20.keystream(
      key: streamKey,
      iv8: iv,
      offset: 32,
      count: ciphertext.count
    )
    var plaintext = [UInt8]()
    plaintext.reserveCapacity(ciphertext.count)
    for i in 0..<ciphertext.count {
      plaintext.append(ciphertext[i] ^ stream[i])
    }
    return plaintext
  }

  private struct Agreement {
    let shared: [UInt8]
    let recipientPublic: [UInt8]
  }

  private static func sharedSecret(
    privateKey: [UInt8],
    ephemeralPublic: [UInt8]
  ) -> Agreement? {
    do {
      let secret = try Curve25519.KeyAgreement.PrivateKey(
        rawRepresentation: Data(privateKey)
      )
      let sender = try Curve25519.KeyAgreement.PublicKey(
        rawRepresentation: Data(ephemeralPublic)
      )
      let shared = try secret.sharedSecretFromKeyAgreement(with: sender)
      // The raw agreement output, deliberately not run through HKDF:
      // HSalsa20 is this construction's own key derivation and
      // substituting a different one would simply not decrypt.
      return Agreement(
        shared: shared.withUnsafeBytes { [UInt8]($0) },
        recipientPublic: [UInt8](secret.publicKey.rawRepresentation)
      )
    } catch {
      return nil
    }
  }
}
